/*
 * Copyright (c) Created by T C L on 2017.5.3.
 */

package com.tcl.study.instructionsresolve;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;

import com.tcl.study.instructionsresolvelibrary.InstructionsResolve;
import com.tcl.study.instructionsresolvelibrary.model.NewsListData;
import com.tcl.study.instructionsresolvelibrary.util.SortUtil;

import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    String result = "{\n"
        + "    \"result\": [\n"
        + "        {\n"
        + "            \"items\": [\n"
        + "                {\n"
        + "                    \"info\": {\n"
        + "                        \"videoUrls\": [],\n"
        + "                        \"h5VideoUrls\": [],\n"
        + "                        \"articlelist\": [],\n"
        + "                        \"liveflage\": 1,\n"
        + "                        \"articleId\": 5829,\n"
        + "                        \"hasMember\": 0,\n"
        + "                        \"memberName\": \"\",\n"
        + "                        \"memberHeadImg\": \"\",\n"
        + "                        \"title\": \"中国网APP测试～\",\n"
        + "                        \"videopicUrl\": \"\",\n"
        + "                        \"describe\": \"当你看到我的时候，你要知道我只是一篇测试文章呦～～～】】】\",\n"
        + "                        \"liveStatus\": \"2\",\n"
        + "                        \"hasVideo\": \"0\",\n"
        + "                        \"hasDate\": 0,\n"
        + "                        \"statuscolor\": \"0xDE0000\",\n"
        + "                        \"status\": \"预告\",\n"
        + "                        \"menuId\": 99,\n"
        + "                        \"menuName\": \"现场\",\n"
        + "                        \"picLinks\": \"\",\n"
        + "                        \"width\": 0,\n"
        + "                        \"height\": 0,\n"
        + "                        \"number\": 0,\n"
        + "                        \"contentType\": 7,\n"
        + "                        \"location\": \"\",\n"
        + "                        \"bgimage\": \"\",\n"
        + "                        \"pubTime\": 1478064005,\n"
        + "                        \"shareTitle\": \"中国网APP测试～\",\n"
        + "                        \"shareContent\": \"当你看到我的时候，你要知道我只是一篇测试文章呦～～～】】】\",\n"
        + "                        \"shareImgUrl\": \"http://m.china.com.cn/images/app/appicon.png\",\n"
        + "                        \"shareUrl\": \"http://wx.china.cn/china-web-h5/live.html?articleId=5829\"\n"
        + "                    },\n"
        + "                    \"days\": [],\n"
        + "                    \"images\": [],\n"
        + "                    \"card\": {\n"
        + "                        \"picLinks\": []\n"
        + "                    },\n"
        + "                    \"type\": \"info\",\n"
        + "                    \"operator\": \"U\",\n"
        + "                    \"_id\": \"59086018606c121df9943727\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"info\": {\n"
        + "                        \"videoUrls\": [],\n"
        + "                        \"h5VideoUrls\": [],\n"
        + "                        \"articlelist\": []\n"
        + "                    },\n"
        + "                    \"days\": [],\n"
        + "                    \"images\": [\n"
        + "                        {\n"
        + "                            \"imgUrl\": \"\",\n"
        + "                            \"describe\": \"3\",\n"
        + "                            \"_id\": \"59086018606c121df9943726\"\n"
        + "                        },\n"
        + "                        {\n"
        + "                            \"imgUrl\": \"\",\n"
        + "                            \"describe\": \"1\",\n"
        + "                            \"_id\": \"59086018606c121df9943725\"\n"
        + "                        }\n"
        + "                    ],\n"
        + "                    \"card\": {\n"
        + "                        \"picLinks\": []\n"
        + "                    },\n"
        + "                    \"type\": \"images\",\n"
        + "                    \"operator\": \"U\",\n"
        + "                    \"_id\": \"59086018606c121df9943724\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"info\": {\n"
        + "                        \"videoUrls\": [],\n"
        + "                        \"h5VideoUrls\": [],\n"
        + "                        \"articlelist\": []\n"
        + "                    },\n"
        + "                    \"days\": [\n"
        + "                        {\n"
        + "                            \"_id\": \"59086018606c121df9943723\"\n"
        + "                        }\n"
        + "                    ],\n"
        + "                    \"images\": [],\n"
        + "                    \"card\": {\n"
        + "                        \"picLinks\": []\n"
        + "                    },\n"
        + "                    \"type\": \"days\",\n"
        + "                    \"operator\": \"U\",\n"
        + "                    \"_id\": \"59086018606c121df9943722\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"info\": {\n"
        + "                        \"videoUrls\": [],\n"
        + "                        \"h5VideoUrls\": [],\n"
        + "                        \"articlelist\": []\n"
        + "                    },\n"
        + "                    \"days\": [],\n"
        + "                    \"images\": [],\n"
        + "                    \"card\": {\n"
        + "                        \"picLinks\": [],\n"
        + "                        \"id\": \"9724\",\n"
        + "                        \"icon\": \"http://wx.china.cn/upload/images/20150425/china_cn_logo.jpg\",\n"
        + "                        \"editor\": \"中国网\",\n"
        + "                        \"content\": \"3\",\n"
        + "                        \"pubTime\": 1493720263,\n"
        + "                        \"location\": \"\",\n"
        + "                        \"unit\": \"\",\n"
        + "                        \"videoUrl\": \"\",\n"
        + "                        \"articleTitle\": \"\",\n"
        + "                        \"articleUrl\": \"\",\n"
        + "                        \"newsType\": 10012,\n"
        + "                        \"shareTitle\": \"中国网APP测试～\",\n"
        + "                        \"shareContent\": \"3\",\n"
        + "                        \"shareImgUrl\": \"http://m.china.com.cn/images/app/logo_ad.png\",\n"
        + "                        \"shareUrl\": \"http://wx.china.cn/china-web-h5/live.html?articleId=5829\"\n"
        + "                    },\n"
        + "                    \"type\": \"card\",\n"
        + "                    \"operator\": \"C\",\n"
        + "                    \"cardId\": \"9724\",\n"
        + "                    \"_id\": \"59086018606c121df9943721\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"info\": {\n"
        + "                        \"videoUrls\": [],\n"
        + "                        \"h5VideoUrls\": [],\n"
        + "                        \"articlelist\": []\n"
        + "                    },\n"
        + "                    \"days\": [],\n"
        + "                    \"images\": [],\n"
        + "                    \"card\": {\n"
        + "                        \"picLinks\": [],\n"
        + "                        \"id\": \"9722\",\n"
        + "                        \"icon\": \"http://wx.china.cn/upload/images/20150425/china_cn_logo.jpg\",\n"
        + "                        \"editor\": \"中国网\",\n"
        + "                        \"content\": \"1\",\n"
        + "                        \"pubTime\": 1493719635,\n"
        + "                        \"location\": \"\",\n"
        + "                        \"unit\": \"\",\n"
        + "                        \"videoUrl\": \"\",\n"
        + "                        \"articleTitle\": \"\",\n"
        + "                        \"articleUrl\": \"\",\n"
        + "                        \"newsType\": 10012,\n"
        + "                        \"shareTitle\": \"中国网APP测试～\",\n"
        + "                        \"shareContent\": \"1\",\n"
        + "                        \"shareImgUrl\": \"http://m.china.com.cn/images/app/logo_ad.png\",\n"
        + "                        \"shareUrl\": \"http://wx.china.cn/china-web-h5/live.html?articleId=5829\"\n"
        + "                    },\n"
        + "                    \"type\": \"card\",\n"
        + "                    \"operator\": \"C\",\n"
        + "                    \"cardId\": \"9722\",\n"
        + "                    \"_id\": \"59086018606c121df9943720\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"info\": {\n"
        + "                        \"videoUrls\": [],\n"
        + "                        \"h5VideoUrls\": [],\n"
        + "                        \"articlelist\": []\n"
        + "                    },\n"
        + "                    \"days\": [],\n"
        + "                    \"images\": [],\n"
        + "                    \"card\": {\n"
        + "                        \"picLinks\": [],\n"
        + "                        \"id\": \"9721\",\n"
        + "                        \"icon\": \"http://wx.china.cn/upload/images/20150425/china_cn_logo.jpg\",\n"
        + "                        \"editor\": \"中国网\",\n"
        + "                        \"content\": \"1\",\n"
        + "                        \"pubTime\": 1493716348,\n"
        + "                        \"location\": \"\",\n"
        + "                        \"unit\": \"\",\n"
        + "                        \"videoUrl\": \"\",\n"
        + "                        \"articleTitle\": \"\",\n"
        + "                        \"articleUrl\": \"\",\n"
        + "                        \"newsType\": 10011,\n"
        + "                        \"shareTitle\": \"中国网APP测试～\",\n"
        + "                        \"shareContent\": \"1\",\n"
        + "                        \"shareImgUrl\": \"http://m.china.com.cn/images/app/logo_ad.png\",\n"
        + "                        \"shareUrl\": \"http://wx.china.cn/china-web-h5/live.html?articleId=5829\"\n"
        + "                    },\n"
        + "                    \"type\": \"card\",\n"
        + "                    \"operator\": \"C\",\n"
        + "                    \"cardId\": \"9721\",\n"
        + "                    \"_id\": \"59086018606c121df994371f\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"articleId\": \"5829\",\n"
        + "            \"index\": \"0\",\n"
        + "            \"_id\": \"59086018606c121df994371e\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"items\": [\n"
        + "                {\n"
        + "                    \"info\": {\n"
        + "                        \"videoUrls\": [],\n"
        + "                        \"h5VideoUrls\": [],\n"
        + "                        \"articlelist\": []\n"
        + "                    },\n"
        + "                    \"days\": [],\n"
        + "                    \"images\": [\n"
        + "                        {\n"
        + "                            \"_id\": \"59086031ff019520d3dcd49d\",\n"
        + "                            \"describe\": \"4\",\n"
        + "                            \"imgUrl\": \"\"\n"
        + "                        },\n"
        + "                        {\n"
        + "                            \"_id\": \"59086031ff019520d3dcd49c\",\n"
        + "                            \"describe\": \"3\",\n"
        + "                            \"imgUrl\": \"\"\n"
        + "                        },\n"
        + "                        {\n"
        + "                            \"_id\": \"59086031ff019520d3dcd49b\",\n"
        + "                            \"describe\": \"1\",\n"
        + "                            \"imgUrl\": \"\"\n"
        + "                        }\n"
        + "                    ],\n"
        + "                    \"card\": {\n"
        + "                        \"picLinks\": []\n"
        + "                    },\n"
        + "                    \"_id\": \"59086031ff019520d3dcd49a\",\n"
        + "                    \"operator\": \"U\",\n"
        + "                    \"type\": \"images\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"info\": {\n"
        + "                        \"videoUrls\": [],\n"
        + "                        \"h5VideoUrls\": [],\n"
        + "                        \"articlelist\": []\n"
        + "                    },\n"
        + "                    \"days\": [],\n"
        + "                    \"images\": [],\n"
        + "                    \"card\": {\n"
        + "                        \"picLinks\": [],\n"
        + "                        \"shareUrl\": \"http://wx.china.cn/china-web-h5/live.html?articleId=5829\",\n"
        + "                        \"shareImgUrl\": \"http://m.china.com.cn/images/app/logo_ad.png\",\n"
        + "                        \"shareContent\": \"4\",\n"
        + "                        \"shareTitle\": \"中国网APP测试～\",\n"
        + "                        \"newsType\": 10012,\n"
        + "                        \"articleUrl\": \"\",\n"
        + "                        \"articleTitle\": \"\",\n"
        + "                        \"videoUrl\": \"\",\n"
        + "                        \"unit\": \"\",\n"
        + "                        \"location\": \"\",\n"
        + "                        \"pubTime\": 1493721128,\n"
        + "                        \"content\": \"4\",\n"
        + "                        \"editor\": \"渠津\",\n"
        + "                        \"icon\": \"http://wx.china.cn/upload/images/20150425/china_cn_logo.jpg\",\n"
        + "                        \"id\": \"9727\"\n"
        + "                    },\n"
        + "                    \"_id\": \"59086031ff019520d3dcd499\",\n"
        + "                    \"cardId\": \"9727\",\n"
        + "                    \"operator\": \"C\",\n"
        + "                    \"type\": \"card\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"_id\": \"59086031ff019520d3dcd498\",\n"
        + "            \"index\": \"1\",\n"
        + "            \"articleId\": \"5829\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"items\": [\n"
        + "                {\n"
        + "                    \"info\": {\n"
        + "                        \"videoUrls\": [],\n"
        + "                        \"h5VideoUrls\": [],\n"
        + "                        \"articlelist\": []\n"
        + "                    },\n"
        + "                    \"days\": [],\n"
        + "                    \"images\": [\n"
        + "                        {\n"
        + "                            \"imgUrl\": \"\",\n"
        + "                            \"describe\": \"3\",\n"
        + "                            \"_id\": \"59086045d899f0215a38aec3\"\n"
        + "                        },\n"
        + "                        {\n"
        + "                            \"imgUrl\": \"\",\n"
        + "                            \"describe\": \"1\",\n"
        + "                            \"_id\": \"59086045d899f0215a38aec2\"\n"
        + "                        }\n"
        + "                    ],\n"
        + "                    \"card\": {\n"
        + "                        \"picLinks\": []\n"
        + "                    },\n"
        + "                    \"type\": \"images\",\n"
        + "                    \"operator\": \"U\",\n"
        + "                    \"_id\": \"59086045d899f0215a38aec1\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"info\": {\n"
        + "                        \"videoUrls\": [],\n"
        + "                        \"h5VideoUrls\": [],\n"
        + "                        \"articlelist\": []\n"
        + "                    },\n"
        + "                    \"days\": [],\n"
        + "                    \"images\": [],\n"
        + "                    \"card\": {\n"
        + "                        \"picLinks\": [],\n"
        + "                        \"id\": \"9727\",\n"
        + "                        \"icon\": \"http://wx.china.cn/upload/images/20150425/china_cn_logo.jpg\",\n"
        + "                        \"editor\": \"田成琳\",\n"
        + "                        \"content\": \"4\",\n"
        + "                        \"pubTime\": 1493721128,\n"
        + "                        \"location\": \"\",\n"
        + "                        \"unit\": \"\",\n"
        + "                        \"videoUrl\": \"\",\n"
        + "                        \"articleTitle\": \"\",\n"
        + "                        \"articleUrl\": \"\",\n"
        + "                        \"newsType\": 10011,\n"
        + "                        \"shareTitle\": \"中国网APP测试～\",\n"
        + "                        \"shareContent\": \"4\",\n"
        + "                        \"shareImgUrl\": \"http://m.china.com.cn/images/app/logo_ad.png\",\n"
        + "                        \"shareUrl\": \"http://wx.china.cn/china-web-h5/live.html?articleId=5829\"\n"
        + "                    },\n"
        + "                    \"type\": \"card\",\n"
        + "                    \"operator\": \"U\",\n"
        + "                    \"cardId\": \"9727\",\n"
        + "                    \"_id\": \"59086045d899f0215a38aec0\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"articleId\": \"5829\",\n"
        + "            \"index\": \"2\",\n"
        + "            \"_id\": \"59086045d899f0215a38aebf\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"items\": [\n"
        + "                {\n"
        + "                    \"info\": {\n"
        + "                        \"videoUrls\": [\n"
        + "                            {\n"
        + "                                \"videoUrl\": \"http://mp4.china.com.cn/video_tide/video/2017/3/14/20173141489463770700_367.mp4\",\n"
        + "                                \"videoline\": \"\"\n"
        + "                            }\n"
        + "                        ],\n"
        + "                        \"h5VideoUrls\": [\n"
        + "                            {\n"
        + "                                \"videoUrl\": \"http://mp4.china.com.cn/video_tide/video/2017/3/14/20173141489463770700_367.mp4\",\n"
        + "                                \"videoline\": \"\"\n"
        + "                            }\n"
        + "                        ],\n"
        + "                        \"articlelist\": [],\n"
        + "                        \"shareUrl\": \"http://wx.china.cn/china-web-h5/live.html?articleId=5829\",\n"
        + "                        \"shareImgUrl\": \"http://m.china.com.cn/images/app/appicon.png\",\n"
        + "                        \"shareContent\": \"当你看到我的时候，你要知道我只是一篇测试文章呦～～～\",\n"
        + "                        \"shareTitle\": \"中国网APP测试～\",\n"
        + "                        \"pubTime\": 1478064005,\n"
        + "                        \"bgimage\": \"\",\n"
        + "                        \"location\": \"\",\n"
        + "                        \"contentType\": 7,\n"
        + "                        \"number\": 0,\n"
        + "                        \"height\": 0,\n"
        + "                        \"width\": 0,\n"
        + "                        \"picLinks\": \"\",\n"
        + "                        \"menuName\": \"现场\",\n"
        + "                        \"menuId\": 99,\n"
        + "                        \"status\": \"预告\",\n"
        + "                        \"statuscolor\": \"0xDE0000\",\n"
        + "                        \"hasDate\": 0,\n"
        + "                        \"hasVideo\": \"1\",\n"
        + "                        \"liveStatus\": \"2\",\n"
        + "                        \"describe\": \"当你看到我的时候，你要知道我只是一篇测试文章呦～～～\",\n"
        + "                        \"videopicUrl\": \"http://wx.china.cn/front/static/images/live_video_bg.png\",\n"
        + "                        \"title\": \"中国网APP测试～\",\n"
        + "                        \"memberHeadImg\": \"\",\n"
        + "                        \"memberName\": \"\",\n"
        + "                        \"hasMember\": 0,\n"
        + "                        \"articleId\": 5829,\n"
        + "                        \"liveflage\": 1\n"
        + "                    },\n"
        + "                    \"days\": [],\n"
        + "                    \"images\": [],\n"
        + "                    \"card\": {\n"
        + "                        \"picLinks\": []\n"
        + "                    },\n"
        + "                    \"_id\": \"59093d1255e8346901fa2b16\",\n"
        + "                    \"operator\": \"U\",\n"
        + "                    \"type\": \"info\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"_id\": \"59093d1255e8346901fa2b15\",\n"
        + "            \"index\": \"3\",\n"
        + "            \"articleId\": \"5829\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"items\": [\n"
        + "                {\n"
        + "                    \"info\": {\n"
        + "                        \"videoUrls\": [\n"
        + "                            {\n"
        + "                                \"videoUrl\": \"http://mp4.china.com.cn/video_tide/video/2017/3/14/20173141489463770700_367.mp4\",\n"
        + "                                \"videoline\": \"\"\n"
        + "                            }\n"
        + "                        ],\n"
        + "                        \"h5VideoUrls\": [\n"
        + "                            {\n"
        + "                                \"videoUrl\": \"http://mp4.china.com.cn/video_tide/video/2017/3/14/20173141489463770700_367.mp4\",\n"
        + "                                \"videoline\": \"\"\n"
        + "                            }\n"
        + "                        ],\n"
        + "                        \"articlelist\": [],\n"
        + "                        \"liveflage\": 1,\n"
        + "                        \"articleId\": 5829,\n"
        + "                        \"hasMember\": 0,\n"
        + "                        \"memberName\": \"\",\n"
        + "                        \"memberHeadImg\": \"\",\n"
        + "                        \"title\": \"中国网APP测试～\",\n"
        + "                        \"videopicUrl\": \"http://wx.china.cn/front/static/images/live_video_bg.png\",\n"
        + "                        \"describe\": \"当你看到我的时候，你要知道我只是一篇测试文章\",\n"
        + "                        \"liveStatus\": \"2\",\n"
        + "                        \"hasVideo\": \"1\",\n"
        + "                        \"hasDate\": 0,\n"
        + "                        \"statuscolor\": \"0xDE0000\",\n"
        + "                        \"status\": \"预告\",\n"
        + "                        \"menuId\": 99,\n"
        + "                        \"menuName\": \"现场\",\n"
        + "                        \"picLinks\": \"\",\n"
        + "                        \"width\": 0,\n"
        + "                        \"height\": 0,\n"
        + "                        \"number\": 0,\n"
        + "                        \"contentType\": 7,\n"
        + "                        \"location\": \"\",\n"
        + "                        \"bgimage\": \"\",\n"
        + "                        \"pubTime\": 1478064005,\n"
        + "                        \"shareTitle\": \"中国网APP测试～\",\n"
        + "                        \"shareContent\": \"当你看到我的时候，你要知道我只是一篇测试文章\",\n"
        + "                        \"shareImgUrl\": \"http://m.china.com.cn/images/app/appicon.png\",\n"
        + "                        \"shareUrl\": \"http://wx.china.cn/china-web-h5/live.html?articleId=5829\"\n"
        + "                    },\n"
        + "                    \"days\": [],\n"
        + "                    \"images\": [],\n"
        + "                    \"card\": {\n"
        + "                        \"picLinks\": []\n"
        + "                    },\n"
        + "                    \"type\": \"info\",\n"
        + "                    \"operator\": \"U\",\n"
        + "                    \"_id\": \"59093d3a69eed56c1dd202e3\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"articleId\": \"5829\",\n"
        + "            \"index\": \"4\",\n"
        + "            \"_id\": \"59093d3a69eed56c1dd202e2\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"items\": [\n"
        + "                {\n"
        + "                    \"info\": {\n"
        + "                        \"videoUrls\": [\n"
        + "                            {\n"
        + "                                \"videoUrl\": \"http://mp4.china.com.cn/video_tide/video/2017/3/14/20173141489463770700_367.mp4\",\n"
        + "                                \"videoline\": \"\"\n"
        + "                            }\n"
        + "                        ],\n"
        + "                        \"h5VideoUrls\": [\n"
        + "                            {\n"
        + "                                \"videoUrl\": \"http://mp4.china.com.cn/video_tide/video/2017/3/14/20173141489463770700_367.mp4\",\n"
        + "                                \"videoline\": \"\"\n"
        + "                            }\n"
        + "                        ],\n"
        + "                        \"articlelist\": [],\n"
        + "                        \"shareUrl\": \"http://wx.china.cn/china-web-h5/live.html?articleId=5829\",\n"
        + "                        \"shareImgUrl\": \"http://m.china.com.cn/images/app/appicon.png\",\n"
        + "                        \"shareContent\": \"当你看到我的时候，你要知道我只是一篇测试文章\",\n"
        + "                        \"shareTitle\": \"中国网APP测试～\",\n"
        + "                        \"pubTime\": 1478064005,\n"
        + "                        \"bgimage\": \"\",\n"
        + "                        \"location\": \"\",\n"
        + "                        \"contentType\": 7,\n"
        + "                        \"number\": 0,\n"
        + "                        \"height\": 0,\n"
        + "                        \"width\": 0,\n"
        + "                        \"picLinks\": \"\",\n"
        + "                        \"menuName\": \"现场\",\n"
        + "                        \"menuId\": 99,\n"
        + "                        \"status\": \"直播中\",\n"
        + "                        \"statuscolor\": \"0xDE0000\",\n"
        + "                        \"hasDate\": 0,\n"
        + "                        \"hasVideo\": \"1\",\n"
        + "                        \"liveStatus\": \"1\",\n"
        + "                        \"describe\": \"当你看到我的时候，你要知道我只是一篇测试文章\",\n"
        + "                        \"videopicUrl\": \"http://wx.china.cn/front/static/images/live_video_bg.png\",\n"
        + "                        \"title\": \"中国网APP测试～\",\n"
        + "                        \"memberHeadImg\": \"\",\n"
        + "                        \"memberName\": \"\",\n"
        + "                        \"hasMember\": 0,\n"
        + "                        \"articleId\": 5829,\n"
        + "                        \"liveflage\": 1\n"
        + "                    },\n"
        + "                    \"days\": [],\n"
        + "                    \"images\": [],\n"
        + "                    \"card\": {\n"
        + "                        \"picLinks\": []\n"
        + "                    },\n"
        + "                    \"_id\": \"59093d493496de6cc738ee92\",\n"
        + "                    \"operator\": \"U\",\n"
        + "                    \"type\": \"info\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"_id\": \"59093d493496de6cc738ee91\",\n"
        + "            \"index\": \"5\",\n"
        + "            \"articleId\": \"5829\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"items\": [\n"
        + "                {\n"
        + "                    \"info\": {\n"
        + "                        \"videoUrls\": [],\n"
        + "                        \"h5VideoUrls\": [],\n"
        + "                        \"articlelist\": [],\n"
        + "                        \"liveflage\": 1,\n"
        + "                        \"articleId\": 5829,\n"
        + "                        \"hasMember\": 0,\n"
        + "                        \"memberName\": \"\",\n"
        + "                        \"memberHeadImg\": \"\",\n"
        + "                        \"title\": \"中国网APP测试～\",\n"
        + "                        \"videopicUrl\": \"\",\n"
        + "                        \"describe\": \"当你看到我的时候，你要知道我只是一篇测试文章\",\n"
        + "                        \"liveStatus\": \"1\",\n"
        + "                        \"hasVideo\": \"0\",\n"
        + "                        \"hasDate\": 0,\n"
        + "                        \"statuscolor\": \"0xDE0000\",\n"
        + "                        \"status\": \"直播中\",\n"
        + "                        \"menuId\": 99,\n"
        + "                        \"menuName\": \"现场\",\n"
        + "                        \"picLinks\": \"\",\n"
        + "                        \"width\": 0,\n"
        + "                        \"height\": 0,\n"
        + "                        \"number\": 0,\n"
        + "                        \"contentType\": 7,\n"
        + "                        \"location\": \"\",\n"
        + "                        \"bgimage\": \"\",\n"
        + "                        \"pubTime\": 1478064005,\n"
        + "                        \"shareTitle\": \"中国网APP测试～\",\n"
        + "                        \"shareContent\": \"当你看到我的时候，你要知道我只是一篇测试文章\",\n"
        + "                        \"shareImgUrl\": \"http://m.china.com.cn/images/app/appicon.png\",\n"
        + "                        \"shareUrl\": \"http://wx.china.cn/china-web-h5/live.html?articleId=5829\"\n"
        + "                    },\n"
        + "                    \"days\": [],\n"
        + "                    \"images\": [],\n"
        + "                    \"card\": {\n"
        + "                        \"picLinks\": []\n"
        + "                    },\n"
        + "                    \"type\": \"info\",\n"
        + "                    \"operator\": \"U\",\n"
        + "                    \"_id\": \"59093d58e145156d022c3b25\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"articleId\": \"5829\",\n"
        + "            \"index\": \"6\",\n"
        + "            \"_id\": \"59093d58e145156d022c3b24\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"items\": [\n"
        + "                {\n"
        + "                    \"info\": {\n"
        + "                        \"videoUrls\": [\n"
        + "                            {\n"
        + "                                \"videoUrl\": \"http://mp4.china.com.cn/video_tide/video/2017/3/14/20173141489463770700_367.mp4\",\n"
        + "                                \"videoline\": \"\"\n"
        + "                            }\n"
        + "                        ],\n"
        + "                        \"h5VideoUrls\": [\n"
        + "                            {\n"
        + "                                \"videoUrl\": \"http://mp4.china.com.cn/video_tide/video/2017/3/14/20173141489463770700_367.mp4\",\n"
        + "                                \"videoline\": \"\"\n"
        + "                            }\n"
        + "                        ],\n"
        + "                        \"articlelist\": [],\n"
        + "                        \"shareUrl\": \"http://wx.china.cn/china-web-h5/live.html?articleId=5829\",\n"
        + "                        \"shareImgUrl\": \"http://m.china.com.cn/images/app/appicon.png\",\n"
        + "                        \"shareContent\": \"当你看到我的时候，你要知道我只是一篇测试文章\",\n"
        + "                        \"shareTitle\": \"中国网APP测试～\",\n"
        + "                        \"pubTime\": 1478064005,\n"
        + "                        \"bgimage\": \"\",\n"
        + "                        \"location\": \"\",\n"
        + "                        \"contentType\": 7,\n"
        + "                        \"number\": 0,\n"
        + "                        \"height\": 0,\n"
        + "                        \"width\": 0,\n"
        + "                        \"picLinks\": \"\",\n"
        + "                        \"menuName\": \"现场\",\n"
        + "                        \"menuId\": 99,\n"
        + "                        \"status\": \"直播中\",\n"
        + "                        \"statuscolor\": \"0xDE0000\",\n"
        + "                        \"hasDate\": 0,\n"
        + "                        \"hasVideo\": \"1\",\n"
        + "                        \"liveStatus\": \"1\",\n"
        + "                        \"describe\": \"当你看到我的时候，你要知道我只是一篇测试文章\",\n"
        + "                        \"videopicUrl\": \"http://wx.china.cn/front/static/images/live_video_bg.png\",\n"
        + "                        \"title\": \"中国网APP测试～\",\n"
        + "                        \"memberHeadImg\": \"\",\n"
        + "                        \"memberName\": \"\",\n"
        + "                        \"hasMember\": 0,\n"
        + "                        \"articleId\": 5829,\n"
        + "                        \"liveflage\": 1\n"
        + "                    },\n"
        + "                    \"days\": [],\n"
        + "                    \"images\": [],\n"
        + "                    \"card\": {\n"
        + "                        \"picLinks\": []\n"
        + "                    },\n"
        + "                    \"_id\": \"59093d6c1c85346e08b0e286\",\n"
        + "                    \"operator\": \"U\",\n"
        + "                    \"type\": \"info\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"_id\": \"59093d6c1c85346e08b0e285\",\n"
        + "            \"index\": \"7\",\n"
        + "            \"articleId\": \"5829\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"items\": [\n"
        + "                {\n"
        + "                    \"info\": {\n"
        + "                        \"videoUrls\": [\n"
        + "                            {\n"
        + "                                \"videoUrl\": \"http://mp4.china.com.cn/video_tide/video/2017/3/14/20173141489463770700_367.mp4\",\n"
        + "                                \"videoline\": \"\"\n"
        + "                            }\n"
        + "                        ],\n"
        + "                        \"h5VideoUrls\": [\n"
        + "                            {\n"
        + "                                \"videoUrl\": \"http://mp4.china.com.cn/video_tide/video/2017/3/14/20173141489463770700_367.mp4\",\n"
        + "                                \"videoline\": \"\"\n"
        + "                            }\n"
        + "                        ],\n"
        + "                        \"articlelist\": [],\n"
        + "                        \"liveflage\": 1,\n"
        + "                        \"articleId\": 5829,\n"
        + "                        \"hasMember\": 0,\n"
        + "                        \"memberName\": \"\",\n"
        + "                        \"memberHeadImg\": \"\",\n"
        + "                        \"title\": \"中国网APP测试～\",\n"
        + "                        \"videopicUrl\": \"http://wx.china.cn/front/static/images/live_video_bg.png\",\n"
        + "                        \"describe\": \"当你看到我的时候，你要知道我只是一篇测试文章\",\n"
        + "                        \"liveStatus\": \"1\",\n"
        + "                        \"hasVideo\": \"1\",\n"
        + "                        \"hasDate\": 0,\n"
        + "                        \"statuscolor\": \"0xDE0000\",\n"
        + "                        \"status\": \"直播中\",\n"
        + "                        \"menuId\": 99,\n"
        + "                        \"menuName\": \"现场\",\n"
        + "                        \"picLinks\": \"http://image.wx.china.cn/upload/images/20170503//_1493777809157_Sv8khKMh.png\",\n"
        + "                        \"width\": 750,\n"
        + "                        \"height\": 422,\n"
        + "                        \"number\": 0,\n"
        + "                        \"contentType\": 7,\n"
        + "                        \"location\": \"\",\n"
        + "                        \"bgimage\": \"\",\n"
        + "                        \"pubTime\": 1478064005,\n"
        + "                        \"shareTitle\": \"中国网APP测试～\",\n"
        + "                        \"shareContent\": \"当你看到我的时候，你要知道我只是一篇测试文章\",\n"
        + "                        \"shareImgUrl\": \"http://m.china.com.cn/images/app/appicon.png\",\n"
        + "                        \"shareUrl\": \"http://wx.china.cn/china-web-h5/live.html?articleId=5829\"\n"
        + "                    },\n"
        + "                    \"days\": [],\n"
        + "                    \"images\": [],\n"
        + "                    \"card\": {\n"
        + "                        \"picLinks\": []\n"
        + "                    },\n"
        + "                    \"type\": \"info\",\n"
        + "                    \"operator\": \"U\",\n"
        + "                    \"_id\": \"59093d9990b3286f5717c979\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"articleId\": \"5829\",\n"
        + "            \"index\": \"8\",\n"
        + "            \"_id\": \"59093d9990b3286f5717c978\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"items\": [\n"
        + "                {\n"
        + "                    \"info\": {\n"
        + "                        \"videoUrls\": [\n"
        + "                            {\n"
        + "                                \"videoUrl\": \"rtmp://pili-publish.wx.china.cn/chinalive/chinalive_5829_1488507651033\",\n"
        + "                                \"videoline\": \"\"\n"
        + "                            }\n"
        + "                        ],\n"
        + "                        \"h5VideoUrls\": [\n"
        + "                            {\n"
        + "                                \"videoUrl\": \"http://pili-live-hls.wx.china.cn/chinalive/chinalive_5829_1488507651033.m3u8\",\n"
        + "                                \"videoline\": \"\"\n"
        + "                            }\n"
        + "                        ],\n"
        + "                        \"articlelist\": [],\n"
        + "                        \"shareUrl\": \"http://wx.china.cn/china-web-h5/live.html?articleId=5829\",\n"
        + "                        \"shareImgUrl\": \"http://m.china.com.cn/images/app/appicon.png\",\n"
        + "                        \"shareContent\": \"当你看到我的时候，你要知道我只是一篇测试文章\",\n"
        + "                        \"shareTitle\": \"中国网APP测试～\",\n"
        + "                        \"pubTime\": 1478064005,\n"
        + "                        \"bgimage\": \"\",\n"
        + "                        \"location\": \"\",\n"
        + "                        \"contentType\": 7,\n"
        + "                        \"number\": 0,\n"
        + "                        \"height\": 422,\n"
        + "                        \"width\": 750,\n"
        + "                        \"picLinks\": \"http://image.wx.china.cn/upload/images/20170503//_1493777809157_Sv8khKMh.png\",\n"
        + "                        \"menuName\": \"现场\",\n"
        + "                        \"menuId\": 99,\n"
        + "                        \"status\": \"直播中\",\n"
        + "                        \"statuscolor\": \"0xDE0000\",\n"
        + "                        \"hasDate\": 0,\n"
        + "                        \"hasVideo\": \"1\",\n"
        + "                        \"liveStatus\": \"1\",\n"
        + "                        \"describe\": \"当你看到我的时候，你要知道我只是一篇测试文章\",\n"
        + "                        \"videopicUrl\": \"http://wx.china.cn/front/static/images/live_video_bg.png\",\n"
        + "                        \"title\": \"中国网APP测试～\",\n"
        + "                        \"memberHeadImg\": \"\",\n"
        + "                        \"memberName\": \"\",\n"
        + "                        \"hasMember\": 0,\n"
        + "                        \"articleId\": 5829,\n"
        + "                        \"liveflage\": 1\n"
        + "                    },\n"
        + "                    \"days\": [],\n"
        + "                    \"images\": [],\n"
        + "                    \"card\": {\n"
        + "                        \"picLinks\": []\n"
        + "                    },\n"
        + "                    \"_id\": \"59093e0c9e21ad73386b220b\",\n"
        + "                    \"operator\": \"U\",\n"
        + "                    \"type\": \"info\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"_id\": \"59093e0c9e21ad73386b220a\",\n"
        + "            \"index\": \"9\",\n"
        + "            \"articleId\": \"5829\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"items\": [\n"
        + "                {\n"
        + "                    \"info\": {\n"
        + "                        \"videoUrls\": [\n"
        + "                            {\n"
        + "                                \"videoUrl\": \"http://mp4.china.com.cn/video_tide/video/2017/3/14/20173141489463770700_367.mp4\",\n"
        + "                                \"videoline\": \"\"\n"
        + "                            }\n"
        + "                        ],\n"
        + "                        \"h5VideoUrls\": [\n"
        + "                            {\n"
        + "                                \"videoUrl\": \"http://mp4.china.com.cn/video_tide/video/2017/3/14/20173141489463770700_367.mp4\",\n"
        + "                                \"videoline\": \"\"\n"
        + "                            }\n"
        + "                        ],\n"
        + "                        \"articlelist\": [],\n"
        + "                        \"liveflage\": 1,\n"
        + "                        \"articleId\": 5829,\n"
        + "                        \"hasMember\": 0,\n"
        + "                        \"memberName\": \"\",\n"
        + "                        \"memberHeadImg\": \"\",\n"
        + "                        \"title\": \"中国网APP测试～\",\n"
        + "                        \"videopicUrl\": \"http://wx.china.cn/front/static/images/live_video_bg.png\",\n"
        + "                        \"describe\": \"当你看到我的时候，你要知道我只是一篇测试文章\",\n"
        + "                        \"liveStatus\": \"1\",\n"
        + "                        \"hasVideo\": \"1\",\n"
        + "                        \"hasDate\": 0,\n"
        + "                        \"statuscolor\": \"0xDE0000\",\n"
        + "                        \"status\": \"直播中\",\n"
        + "                        \"menuId\": 99,\n"
        + "                        \"menuName\": \"现场\",\n"
        + "                        \"picLinks\": \"http://image.wx.china.cn/upload/images/20170503//_1493777809157_Sv8khKMh.png\",\n"
        + "                        \"width\": 750,\n"
        + "                        \"height\": 422,\n"
        + "                        \"number\": 0,\n"
        + "                        \"contentType\": 7,\n"
        + "                        \"location\": \"全国人大,政协\",\n"
        + "                        \"bgimage\": \"\",\n"
        + "                        \"pubTime\": 1478064005,\n"
        + "                        \"shareTitle\": \"中国网APP测试～\",\n"
        + "                        \"shareContent\": \"当你看到我的时候，你要知道我只是一篇测试文章\",\n"
        + "                        \"shareImgUrl\": \"http://m.china.com.cn/images/app/appicon.png\",\n"
        + "                        \"shareUrl\": \"http://wx.china.cn/china-web-h5/live.html?articleId=5829\"\n"
        + "                    },\n"
        + "                    \"days\": [],\n"
        + "                    \"images\": [],\n"
        + "                    \"card\": {\n"
        + "                        \"picLinks\": []\n"
        + "                    },\n"
        + "                    \"type\": \"info\",\n"
        + "                    \"operator\": \"U\",\n"
        + "                    \"_id\": \"59093e3e84d13875206a4413\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"articleId\": \"5829\",\n"
        + "            \"index\": \"10\",\n"
        + "            \"_id\": \"59093e3e84d13875206a4412\"\n"
        + "        }\n"
        + "    ]\n"
        + "}";

    InstructionsResolve instructionsResolve = InstructionsResolve.getInstance();
    NewsListData newsListData = instructionsResolve.parsesAndSave(result);
    List<NewsListData.NewsItemData> newsItemDatas = newsListData.getResult();

    String location = newsItemDatas.get(newsItemDatas.size() - 1)
        .getItems()
        .get(newsItemDatas.get(newsItemDatas.size() - 1).getItems().size() - 1)
        .getInfo()
        .getLocation();

    List<NewsListData.NewsItemData.Item.Day> dayList = newsItemDatas.get(newsItemDatas.size() - 1)
        .getItems()
        .get(newsItemDatas.get(newsItemDatas.size() - 1).getItems().size() - 1)
        .getDays();

    List<NewsListData.NewsItemData.Item.Card> cards = getCard(newsItemDatas);
    List<NewsListData.NewsItemData.Item.Card> filteredCards = SortUtil.queryByEditor(cards, "田成琳");
    List<NewsListData.NewsItemData.Item.Card> filteredLocationCards = SortUtil.queryByLocation(
        cards, "全国人大");
    List<NewsListData.NewsItemData.Item.Card> filteredTimeCards = SortUtil.queryByDate(cards,
        dayList.get(0));

  }

  public List<NewsListData.NewsItemData.Item.Card> getCard(
      List<NewsListData.NewsItemData> newsItemDatas) {

    List<NewsListData.NewsItemData.Item.Card> cards = new ArrayList<>();
    for (int i = 0; i < newsItemDatas.size(); i++) {
      for (int j = 0; j < newsItemDatas.get(i).getItems().size(); j++) {
        if (newsItemDatas.get(i).getItems().get(j).getType().equals("card")) {
          if (newsItemDatas.get(i).getItems().get(j).getOperator().equals("C")) {
            boolean isExist = false;
            for (int k = 0; k < cards.size(); k++) {
              if (cards.get(k)
                  .getId()
                  .equals(newsItemDatas.get(i).getItems().get(j).getCardId())) {
                isExist = true;
                break;
              }
            }
            if (!isExist) {
              cards.add(newsItemDatas.get(i).getItems().get(j).getCard());
            }
          } else if (newsItemDatas.get(i).getItems().get(j).getOperator().equals("U")) {
            int position = -1;
            for (int k = 0; k < cards.size(); k++) {
              if (cards.get(k)
                  .getId()
                  .equals(newsItemDatas.get(i).getItems().get(j).getCardId())) {
                position = k;
                break;
              }
            }
            if (position != -1) {
              cards.set(position, newsItemDatas.get(i).getItems().get(j).getCard());
            }
          } else {
            int position = -1;
            for (int k = 0; k < cards.size(); k++) {
              if (cards.get(k)
                  .getId()
                  .equals(newsItemDatas.get(i).getItems().get(j).getCardId())) {
                position = k;
                break;
              }
            }
            if (position != -1) {
              cards.remove(position);
            }
          }
        }
      }
    }
    return cards;
  }

}
